
services:
  app:
    image: ${REGISTRY}/${IMAGE_NAME}-aggregator:${IMAGE_TAG}
    container_name: trustai-backend
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_HOST: ${CONFIG_SERVER_HOST:-69.62.76.124}
      SPRING_CLOUD_CONFIG_URI: http://$CONFIG_SERVER_HOST:8888
      SPRING_CONFIG_IMPORT: configserver:http://$CONFIG_SERVER_HOST:8888/
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    networks:
#      - backend
    restart: unless-stopped
    volumes:
      - /home/trustaiapp/logs:/app/logs              # mount host logs directory (./logs → relative to where you run docker-compose up on the host.)
      - /home/uploads:/app/uploads


#networks:
#  backend:
#    external: true